ALTER TABLE FileQc ADD COLUMN qcDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE FUNCTION update_qcDate() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
  BEGIN
    NEW.qcDate = NOW();
    RETURN NEW;
  END;
$$;

DROP TRIGGER IF EXISTS fileQc_add_qcDate_timestamp ON qcdb.FileQc;
CREATE TRIGGER fileQc_add_qcDate_timestamp BEFORE INSERT OR UPDATE ON FileQc FOR EACH ROW EXECUTE PROCEDURE update_qcDate();
